steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME', '.']
  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME']
  # Manual Deploy image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        '$REPO_NAME-$BRANCH_NAME',
        '--image',
        'gcr.io/$PROJECT_ID/$REPO_NAME-$BRANCH_NAME',
        '--region',
        '$LOCATION',
        '--platform',
        'managed',
        '--port',
        '80',
        '--update-env-vars=API_PORT=80',
        '--update-secrets=REDIS_URI=REDIS_URI:1,MONGODB_URI=MONGODB_URI:1',
        '--allow-unauthenticated'
      ]
