FROM node:17-alpine3.14

ENV NODE_ENV development

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

ARG API_PORT=80
ENV API_PORT=$API_PORT
EXPOSE $API_PORT

CMD ["npm", "run", "dev"]
